name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "python/examples/*.gif"
      - "python/examples/*.apng"
      - "python/examples/*.mp4"
      - "python/examples/*.png"
      - "scripts/regenerate_gifs.py"
      - "img/**"
      - "images/**"
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
      max-parallel: 1
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
      - run: pixi run build
      - run: pixi run test
      - run: pixi run test-fpe

  fpe-mojo-tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
      max-parallel: 1
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
      - run: pixi run test-fpe

