name: Publish
on:
  push:
    tags: ["v*"]

jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            target: linux-64
          - platform: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.platform }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.0
      - run: pixi publish --target-channel https://prefix.dev/fpe-engine
